# Generated by Django 3.2.5 on 2021-07-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICE_CENTRE',
            fields=[
                ('service_centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=10)),
                ('services_provided', models.CharField(choices=[('Bike_Service', 'Bike_Service'), ('Car_Service', 'Car_Service')], max_length=20)),
                ('service_centre_address', models.CharField(max_length=10)),
                ('station_phoneNumber', models.CharField(max_length=10)),
                ('bike_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SERVICING_DETAILS',
            fields=[
                ('servicing_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_done', models.BooleanField()),
                ('service_details', models.TextField()),
                ('parts_changed', models.CharField(max_length=10)),
                ('bill_amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.PositiveIntegerField()),
                ('payment_description', models.CharField(max_length=10)),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER_DETAILS',
            fields=[
                ('customer_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('bike_registered_number', models.CharField(max_length=10)),
                ('user_bike_type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER_APPOINTMENT',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_address', models.CharField(max_length=10)),
                ('pickup_time', models.DateTimeField()),
                ('drop_off_address', models.CharField(max_length=10)),
                ('drop_off_time', models.DateTimeField()),
                ('user_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='BIKE_SALE_DETAILS',
            fields=[
                ('bike_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bike_type', models.CharField(choices=[('Regular', 'Regular'), ('Sports', 'Sports'), ('No_Gear', 'No_Gear')], max_length=10)),
                ('bike_brand', models.CharField(max_length=10)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_colour', models.CharField(choices=[('Blue', 'Blue'), ('White', 'White'), ('Green', 'Green'), ('Black', 'Black')], max_length=10)),
                ('bike_registered_number', models.PositiveIntegerField()),
                ('is_bike_available', models.BooleanField()),
                ('bike_service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.service_centre')),
            ],
        ),
        migrations.CreateModel(
            name='BIKE_DELIVERY_DETAILS',
            fields=[
                ('delivery_location_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('delivery_location_address', models.CharField(max_length=10)),
                ('delivery_setOff_time', models.DateTimeField(max_length=10)),
                ('delivery_arrival_time', models.DateTimeField()),
                ('bike_type', models.CharField(choices=[('Regular', 'Regular'), ('Sports', 'Sports'), ('No_Gear', 'No_Gear')], max_length=10)),
                ('bike_brand', models.CharField(max_length=10)),
                ('bike_model', models.CharField(max_length=10)),
                ('bike_colour', models.CharField(choices=[('Blue', 'Blue'), ('White', 'White'), ('Green', 'Green'), ('Black', 'Black')], max_length=10)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.bike_sale_details')),
            ],
        ),
        migrations.CreateModel(
            name='ALARM_APPOINTMENT',
            fields=[
                ('alarm_id', models.AutoField(primary_key=True, serialize=False)),
                ('alarm_timeDate', models.DateTimeField()),
                ('user_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_app.customer_details')),
            ],
        ),
    ]
