# Generated by Django 3.2.5 on 2021-07-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CUSTOMER_DETAILS',
            new_name='CustomerDetails',
        ),
    ]
