# Generated by Django 3.2.5 on 2021-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0002_alter_customer_appointment_user_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT_SERVICE',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
