# Generated by Django 3.2.5 on 2021-07-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0002_rename_customer_details_customerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
    ]
