# Generated by Django 3.2.5 on 2021-07-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0003_rename_customerdetails_customerdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetail',
            options={'verbose_name': 'Customer Details'},
        ),
    ]
