# Generated by Django 3.2.5 on 2021-07-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0004_alter_customerdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_appointment',
            options={'verbose_name': 'Customer Appointment'},
        ),
        migrations.AlterModelOptions(
            name='customerdetail',
            options={'verbose_name': 'Customer Detail'},
        ),
    ]
