# Generated by Django 3.2.5 on 2021-07-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0005_auto_20210719_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetail',
            new_name='CUSTOMER_DETAIL',
        ),
        migrations.AlterModelOptions(
            name='alarm_appointment',
            options={'verbose_name': 'Alarm Appointment'},
        ),
        migrations.AlterModelOptions(
            name='bike_delivery_details',
            options={'verbose_name': 'Bike Delivery Detail'},
        ),
        migrations.AlterModelOptions(
            name='bike_sale_details',
            options={'verbose_name': 'Bike Sale Details'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='service_centre',
            options={'verbose_name': 'Service Centre'},
        ),
        migrations.AlterModelOptions(
            name='servicing_details',
            options={'verbose_name': 'Servicing Details'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users'},
        ),
    ]
