# Generated by Django 3.2.5 on 2021-07-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0007_auto_20210719_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
    ]
