# Generated by Django 3.2.5 on 2021-07-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='user_bike_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sports', 'Sports'), ('No_Gear', 'No_Gear')], max_length=10),
        ),
    ]
