# Generated by Django 3.2.5 on 2021-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0009_alter_customer_detail_user_bike_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
