# Generated by Django 3.2.5 on 2021-07-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0011_auto_20210721_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_detail',
            old_name='mobile_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
